[features]
seeds = false
skip-lint = false

[programs.localnet]
simchain_wallet = "81K4v8JgJ64hz95gdkY2YFCc5PYkJa93VuQgPweu6usZ"

[programs.devnet]
simchain_wallet = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/monehin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.1" 