[features]
seeds = false
skip-lint = false

[programs.localnet]
simchain_wallet = "DMaWHy1YmFNNKhyMWaTGpY76hKPdAhu4ExMHTGHU2j8r"

[programs.devnet]
simchain_wallet = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[clusters]
localnet = "http://127.0.0.1:8898"

[toolchain]
anchor_version = "0.31.1" 